app = "samma-frontend"

[build]
  dockerfile = "../Dockerfile.frontend"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls","http"]
    port = 443


# Optional: set healthcheck path
[checks]
  timeout = 2000
  interval = 10000
  grace_period = 10000
  restart_limit = 0
  [[checks.http]]
    path = "/api/"
    method = "get"
    protocol = "http"
    port = 3000
